# web server config
server:
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB


# data source config
spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource          # HikariCP data source framework
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql driver for mysql 8
    hikari:
      connection-timeout: 30000             # timeout for waiting for a connection from the pool (milliseconds)
      minimum-idle: 5                       # minimum number of idle connections
      maximum-pool-size: 20                 # maximum number of connections
      auto-commit: true                     # automatically commit statements
      idle-timeout: 600000                  # maximum time a connection can be idle before being closed (milliseconds)
      pool-name: DateSourceHikariCP         # name of the connection pool
      max-lifetime: 1800000                 # maximum lifetime of a connection (milliseconds)
      connection-test-query: SELECT 1       # test query to validate a connection

# mybatis config
mybatis:
  type-aliases-package: com.ziyuan.pojo          # package of all pojo
  mapper-locations: classpath:mapper/*.xml          # files under resources are loaded in classpath

spring.kafka.bootstrap-servers: 192.168.83.142:9092
spring.kafka.producer.retries: 3
spring.kafka.producer.batch-size: 16384
spring.kafka.producer.buffer-memory: 33554432
spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks: 1
spring.kafka.listener.ack-mode: manual
spring.kafka.listener.concurrency: 5
spring.kafka.consumer.enable-auto-commit: false
spring.kafka.consumer.auto-offset-reset: earliest
spring.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
