# web server config
server:
  port: 8088

# data source config
spring:
  datasource:
    url: jdbc:mysql://192.168.83.138:3306/tiny-twitter-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: password
  kafka:
    bootstrap-servers: 192.168.83.142:9092

# mybatis config
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # print sql in console by logger

# snowflake id generator config
snowflake:
  machineId: 1
  datacenterId: 2
  sequenceBit: 10
  machineBit: 10
  datacenterBit: 2
