# web server config
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB


# data source config
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource          # HikariCP data source framework
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql driver for mysql 8
    url: jdbc:mysql://192.168.83.138:3306/tiny-twitter-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: password
    hikari:
      connection-timeout: 30000             # timeout for waiting for a connection from the pool (milliseconds)
      minimum-idle: 5                       # minimum number of idle connections
      maximum-pool-size: 20                 # maximum number of connections
      auto-commit: true                     # automatically commit statements
      idle-timeout: 600000                  # maximum time a connection can be idle before being closed (milliseconds)
      pool-name: DateSourceHikariCP         # name of the connection pool
      max-lifetime: 1800000                 # maximum lifetime of a connection (milliseconds)
      connection-test-query: SELECT 1       # test query to validate a connection

# mybatis config
mybatis:
  type-aliases-package: com.ziyuan.pojo          # package of all pojo
  mapper-locations: classpath:mapper/*.xml          # files under resources are loaded in classpath